const router = require('express').Router();
const models = require('../../db/models');
const { formatBookingDates, hasNoBookingOverlap } = require('../../utils/booking-dates');


router.get('/current', async (req, res) => {
    try {
        const user = req.user;
        if (user) {
            const bookings = await models.Booking.findAll({
                where: { userId: user.id },
                include: [{ model: models.Spot }]
            });
            return res.status(200).json({ Bookings: bookings });
        }
        res.status(401).json({ message: 'Not Permitted'});
    } catch (err) {
        res.status(500).json({ message: 'Something went wrong'});
    }
});

router.put('/:bookingId', async (req, res, next) => {
    const { startDate:start, endDate:end } = req.body;
    const { startDate, endDate } = formatBookingDates({ start, end });
    const isValidBookingDate = startDate < endDate;
    const booking = await models.Booking.findByPk(req.params.bookingId);
    if (!req.user && req.user.id !== booking.userId) {
        res.status(403).json({
            message: "Booking owned by other User", // (or "Validation error" if generated by Sequelize),
            errors: {
              username: "userId and bookingID do not match"
            }
        });
    }
    const isAllowedToBook = hasNoBookingOverlap([booking], startDate, endDate);
    if (!isValidBookingDate || !isAllowedToBook) {
        return res.status(403).json({
            message: "Can not book"
        });
    }
    if (startDate) {
        booking.startDate = startDate;
    }
    if (endDate) {
        booking.endDate = endDate;
    }
    await booking.save();
    res.status(200).json(booking);
});
router.delete('/:bookingId', async (req, res, next) => {
    const booking = await models.Booking.findByPk(req.params.bookingId);
    if (!booking) {
        res.status(404);
        return res.json({
            message: "Booking not Found"
        });
    }
    if (req.user.id !== booking.userId) {
        res.status(403);
        return res.json({
            message: "Bookking owned by other user", // (or "Validation error" if generated by Sequelize),
            errors: {
              username: "userId and bookingID do not match"
            }
        });
    }
    await booking.destroy();
    return res.status(200).json({
        message: "Booking deleted"
    });
});
// delete (testing)
router.delete('/spot/:spotId', async (req, res) => {
    const spot = await models.Spot.findByPk(Number(req.params.spotId));
    await spot.destroy();
    res.json({
        message: "Spot deleted",
        Spot: spot
    });
});    
    module.exports = router;
    